### ISSUE TITLE
Implement proper batching (without repeats) for hypernetwork inference

### ISSUE THREAD

**Issue by KathyHaem** [bminixhofer/zett#5]
Hi there,

I tried running the transfer.py script with transfer to a (relatively) large vocabulary and found myself very confused by the batching behaviour and constant OOMs I was getting. 
Eventually I figured out that this bit in the paper:

"To keep runtime comparable between training the model with hypernetwork and direct training (without hypernetwork), we run hypernetwork inference only for a subset of k = 16384 tokens in the continued training case. The subset consists of all tokens occurring in the batch, plus a uniform sample of those that do not occur." 

Describes exactly what the batching in transfer.py does, but I'm still not sure _why_. As-is, running transfer.py will inference over the whole vocabulary anyway afaict, so it's not actually matching the case described in that paragraph.

I'm also not really clear on why we want to predict each token around ten times (as per the default settings) when batching but not when doing simultaneous inference over the whole vocab. Is this meant to regularise the inference? Would it be safe to implement a more standard batching if I just want the memory-saving benefits of it?

**Comment by bminixhofer** [comment]
Hi, thanks for bringing this up.

This is actually not directly related to this snippet from the paper.

The batching in transfer.py is a remnant of when we used inter-token attention, and the tokens in the same batch thus influenced each others' embedding (then, if we have to batch, it also makes sense to average across a couple batches). This is not the case anymore.

So

> Would it be safe to implement a more standard batching if I just want the memory-saving benefits of it?

This is perfectly safe and we should do it. If you want to go for it a PR would be great. I might get around to it myself but can't give a timeline.

**Comment by KathyHaem** [comment]
I see, thanks for clarifying. I'll give it a go when I have time and probably open a PR, hopefully sometime this week (or next).

**Comment by bminixhofer** [comment]
Closing as completed.
